services:

  api:
    image: syntaqx/api
    build: .
    ports:
      - '8080'
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:alpine
    ports:
      - '5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
