name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:

  build:
    uses: ./.github/workflows/docker.yml
    with:
      push: true
    secrets: inherit

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://api.syntaqx.com/
    env:
      HEROKU_APP_NAME: "syntaqx-api"
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Sign into the Container Registry
        run: heroku container:login
      -
        name: Pull the previously built image
        run: docker pull ${{ needs.build.outputs.image }}
      -
        name: Push an image to Heroku
        run: |
          docker tag ${{ needs.build.outputs.image }} registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web
          docker push registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web
      -
        name: Release to Heroku
        run: heroku container:release web --app ${{ env.HEROKU_APP_NAME }}
